[package]
name = "wiiload"
version = "0.4.0"
edition = "2024"
rust-version = "1.85"
authors = ["Manuel Quarneti <mq1@ik.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mq1/wiiload-rs"
homepage = "https://github.com/mq1/wiiload-rs"
description = "A minimal wiiload implementation in rust"

[features]
default = ["compression", "cli"]
compression = ["dep:miniz_oxide"]
cli = ["dep:lexopt", "dep:async-net"]

[dependencies]
thiserror = "2"
futures-lite = "2"
async-net = { version = "2", optional = true }
miniz_oxide = { version = "0.9", optional = true }
lexopt = { version = "0.3", optional = true }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
