name: Release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: i686-unknown-linux-gnu
            runner: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            runner: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
          - target: i686-pc-windows-msvc
            runner: windows-latest
          - target: aarch64-pc-windows-msvc
            runner: windows-latest
          - target: aarch64-apple-darwin
            runner: macos-latest
          - target: x86_64-apple-darwin
            runner: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.94
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: |
          cargo build --locked --release --target ${{ matrix.target }} --features cli
          cp target/${{ matrix.target }}/release/wiiload wiiload-${{ matrix.target }}

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.target }}
          path: wiiload-${{ matrix.target }}

  release:
    name: Create GitHub Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-slim
    needs: [build]
    steps:
      - name: Download distributables
        uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          prerelease: ${{ contains(env.VERSION_NAME, 'alpha') || contains(env.VERSION_NAME, 'beta') || contains(env.VERSION_NAME, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
